# AI-Lab: 10
### Rollnumber: SU92-BSAIM-f24-024
### Name: Ali Husnain

<div class="alert alert-block alert-info">
    Using <b>Python</b> version 3.13.3
</div>

<div class="alert alert-block alert-info">
    Import <b>Libraries</b>
</div>

In [1]:
# !pip install pandas
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

<div class="alert alert-block alert-info">
    1. <b>Data Gathering</b> : <a href="https://www.kaggle.com/datasets/shree1992/housedata">Click Me</a>
    <br>
    2. <b>Data Loading</b>
</div>

In [2]:
df = pd.read_csv("data.csv")
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

<div class="alert alert-block alert-info">
    3. <b>Data Exploration</b>
</div>

In [3]:
df.head(2)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5

In [4]:
df.tail(2)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [5]:
df.columns

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='object')

In [6]:
df.count()

brand                823
processor_brand      823
processor_name       823
processor_gnrtn      823
ram_gb               823
ram_type             823
ssd                  823
hdd                  823
os                   823
os_bit               823
graphic_card_gb      823
weight               823
warranty             823
Touchscreen          823
msoffice             823
Price                823
rating               823
Number of Ratings    823
Number of Reviews    823
dtype: int64

In [7]:
df.describe()

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [9]:
df.shape
print(f"Number of Rows: {df.shape[0]} and Number of Columns: {df.shape[1]}")

Number of Rows: 823 and Number of Columns: 19

In [11]:
df.nunique()

brand                  8
processor_brand        3
processor_name        11
processor_gnrtn        8
ram_gb                 4
ram_type               6
ssd                    7
hdd                    4
os                     3
os_bit                 2
graphic_card_gb        5
weight                 3
warranty               4
Touchscreen            2
msoffice               2
Price                405
rating                 5
Number of Ratings    282
Number of Reviews    135
dtype: int64

In [12]:
df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

<div class="alert alert-block alert-info">
    4. <b>Data Pre-Processing</b>
</div>

<div class="alert alert-block alert-warning">
    4.1. <b>Manage Null Values</b>
</div>

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

<div class="alert alert-block alert-warning">
    4.2. <b>Manage Data Types</b>
</div>

In [24]:
def extract_number(series):
    return (
        series.astype(str)
              .str.extract(r'(\d+)')   # extract digits
              .fillna(0)
              .astype(int)
    )

In [25]:
def convertFloatToInt(df, columns):
    for col in columns:
        df[col] = extract_number(df[col])

In [27]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

def convertObjToInt(df, columns):
    for col in columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        encoders[col] = le   # store encoder for future use

In [28]:
numeric_string_cols = [
    'ram_gb','ssd','hdd','graphic_card_gb',
    'warranty','processor_gnrtn','os_bit'
]

convertFloatToInt(df, numeric_string_cols)

In [29]:
categorical_cols = [
    'brand','processor_brand','processor_name','ram_type',
    'os','weight','Touchscreen','msoffice','rating'
]

convertObjToInt(df, categorical_cols)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    int64
 1   processor_brand    823 non-null    int64
 2   processor_name     823 non-null    int64
 3   processor_gnrtn    823 non-null    int64
 4   ram_gb             823 non-null    int64
 5   ram_type           823 non-null    int64
 6   ssd                823 non-null    int64
 7   hdd                823 non-null    int64
 8   os                 823 non-null    int64
 9   os_bit             823 non-null    int64
 10  graphic_card_gb    823 non-null    int64
 11  weight             823 non-null    int64
 12  warranty           823 non-null    int64
 13  Touchscreen        823 non-null    int64
 14  msoffice           823 non-null    int64
 15  Price              823 non-null    int64
 16  rating             823 non-null    int64
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(19)
memory usage: 122.3 KB

In [31]:
df.head(2)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,10,4,1,0,1024,2,64,0,0,0,0,0,34649,1,3,0
1,5,1,1,10,4,1,0,1024,2,64,0,0,0,0,0,38999,2,65,5

In [32]:
df.to_csv('processed_data.csv', index=False, header=True)

In [33]:
df = pd.read_csv('processed_data.csv')
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,10,4,1,0,1024,2,64,0,0,0,0,0,34649,1,3,0
1,5,1,1,10,4,1,0,1024,2,64,0,0,0,0,0,38999,2,65,5
2,5,1,1,10,4,1,0,1024,2,64,0,0,0,0,0,39999,2,8,1
3,1,1,2,10,8,1,512,0,2,32,2,0,0,0,0,69990,2,0,0
4,1,1,0,0,4,1,0,512,2,64,0,0,0,0,0,26990,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,0,4,1,1024,0,2,64,0,0,1,0,0,135990,2,0,0
819,1,0,10,0,4,1,1024,0,2,64,0,0,1,0,0,144990,2,0,0
820,1,0,10,0,4,1,1024,0,2,64,4,0,1,0,0,149990,2,0,0
821,1,0,10,0,4,1,1024,0,2,64,4,0,1,0,0,142990,2,0,0
822,5,0,8,10,8,1,512,0,0,64,0,2,0,0,0,57490,3,18,4

In [49]:
from sklearn.model_selection import train_test_split

X = df.drop("Price", axis=1)
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
import joblib
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=300, random_state=42)
rf.fit(X_train, y_train)
joblib.dump(rf, "Laptop_price_model.pkl")

['Laptop_price_model.pkl']

<div style="background-color: gray; width:100%; height:10vh; margin-bottom:2%;">
        Header
</div>

<div style="width:100%; height: 30vh;">
    <div style="background-color: gray; float:left; width:25%; height:30vh;">
        <center>Left Section</center>
    </div>
    <div style="background-color: gray; float:right; width:73%; height:30vh;">
        <center>Right Section</center>
        <div style="background-color: silver; margin:2%">
            Sub-Section 1
        </div>
        <div style="background-color: silver; margin:2%">
            Sub-Section 2
        </div>
        <div style="background-color: silver; margin:2%">
            Sub-Section 3
        </div>
        <div style="background-color: silver; margin:2%">
            Sub-Section 4
        </div>
        <div style="background-color: silver; margin:2%">
            Sub-Section 5
        </div>
    </div>
</div>

<div style="background-color: gray; width:100%; height:10vh; margin-top: 2%;">
        Footer
</div>

<div class="alert alert-block alert-danger">
    BREAK: <b>10:15</b>
</div>